### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by Plackys** [toarch7/nt-recreated-public#1]
when i try to compile the game, almost every object and script were broken, and i can't compile the game because of that, do i need to use the paid version of gms2? cuz im using the free version of gms2

**Comment by toarch7** [comment]
you can't compile the game from this source because it misses resources for sprites and sounds due to legal resons. if you know how, you can extract them from official release and do the rest of the work (like assigning images and replacing sound resources).

mentioning that, in some future I hope to finish my automatic export & replacement script but as of this day this project isn't my top priority.
